---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: promtail
      version: '>=6.0.0'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # DaemonSet runs on every node to collect logs
    daemonset:
      enabled: true
    
    config:
      # Send logs to Loki
      clients:
        - url: http://loki:3100/loki/api/v1/push
          tenant_id: ""
      
      # Scrape configs for Kubernetes pod logs
      snippets:
        scrapeConfigs: |
          # Pods with logging=true label
          - job_name: kubernetes-pods
            pipeline_stages:
              - cri: {}
              - labeldrop:
                  - filename
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              # Only scrape pods with logging=true label
              - source_labels: [__meta_kubernetes_pod_label_logging]
                action: keep
                regex: "true"
              # Add namespace label
              - source_labels: [__meta_kubernetes_namespace]
                target_label: namespace
              # Add pod name label
              - source_labels: [__meta_kubernetes_pod_name]
                target_label: pod
              # Add container name label
              - source_labels: [__meta_kubernetes_pod_container_name]
                target_label: container
              # Add app label if exists
              - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                target_label: app
              # Add job=namespace/app
              - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_app_kubernetes_io_name]
                separator: /
                target_label: job
                replacement: $1
              # File path
              - source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
                target_label: __path__
                replacement: /var/log/pods/*$1*/*/*.log
          
          # System pods (kube-system namespace - always collected)
          - job_name: kubernetes-system-pods
            pipeline_stages:
              - cri: {}
              - labeldrop:
                  - filename
            kubernetes_sd_configs:
              - role: pod
                namespaces:
                  names:
                    - kube-system
                    - flux-system
            relabel_configs:
              - source_labels: [__meta_kubernetes_namespace]
                target_label: namespace
              - source_labels: [__meta_kubernetes_pod_name]
                target_label: pod
              - source_labels: [__meta_kubernetes_pod_container_name]
                target_label: container
              - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                target_label: app
              - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_app_kubernetes_io_name]
                separator: /
                target_label: job
              - source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
                target_label: __path__
                replacement: /var/log/pods/*$1*/*/*.log
    
    # Resources
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    
    # Tolerations to run on all nodes
    tolerations:
      - effect: NoSchedule
        operator: Exists
