apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: victoriametrics
  namespace: flux-system
spec:
  interval: 24h
  url: https://victoriametrics.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoriametrics-k8s-stack
  namespace: monitoring
spec:
  interval: 30m
  chart: 
    spec:
      chart: victoria-metrics-k8s-stack
      version: ">=0.63.0"
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    vmsingle:
      spec:
        retentionPeriod: "12" #months
        storage:
          resources:
            requests:
              storage: 150Gi
    vmagent:
      serviceScrapeSelector: {}
      podScrapeSelector: {}
      staticScrapeSelector: {}
    grafana:
      enabled: true
      persistence:
        enabled: true
    nameOverride: vmks

