apiVersion: v1
kind: Secret
metadata:
    name: netbox-email
    namespace: netbox
type: Opaque
stringData:
    email-password: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbmVIV1ZpMm1MNUpwbnZW
            RHRsckJFc2srMzhMMVZiYmFtWE9xbXV1d2d3CnhQMVFabXhpYVFRdTRubXBPelIz
            eVp0dzd1dlc5SW13bE9UajNzMWNXelEKLS0tIGsvZk9XUzluaGF2a0J6Y0pyNGxX
            Z014TFFncmwwc3BReFV5YWsxRUkweWMKIEFB2SsQL0zBlCf0+9hsg/FZP9rmVJ1H
            715sqhvBnvZtUxA6r2eBouQiuL8Wmd65YnlIaDemVGvtxqkH97f6VQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fmqw6vxjs3sx6gatvfxftpy6sg8cyy0sw2m9w9nqh5wxh8ck8gpqrx9s8y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T20:55:23Z"
    mac: ENC[AES256_GCM,data:tTl27gACAfwrR9a5ZqUMEhXz0gk5N2BX4V4HZ9bSCow9tD8bh4st70ZACstgWMB9mtPWuNSxGgQ5ESDUkZIQD3qz1curKB2KDrfJb1mZc8IfBqewXt3Xtv4iVZ58oFt468VrzMBiBJuWhjtQpQSUtCHMdkK/AkTiH+a9+6FbYp0=,iv:HytxG33wIAwryet0qH7lDvuqR2kMvlR7/cW4e4C/PS0=,tag:fLGSflK+zQHlV4VcJVSOPA==,type:str]
    version: 3.13.3
