apiVersion: v1
kind: Secret
metadata:
    name: netbox-config
    namespace: netbox
type: Opaque
stringData:
    secret_key: ENC[AES256_GCM,data:tA/Iu4tIi4MbFszeBQmRtjNOJycAYlFqn1fWS0jOk7Pw+Z+OxgzkyhXCEgWYJCw+traxmejkGXtpTB15o6FuNw==,iv:B1ApShC/BQ4ryaEvhN3jQkZtHJ73kW/Lmx1I2ReciNg=,tag:XIfz4AVDbLI/Br8IyxDIJw==,type:str]
    api_token_peppers: ENC[AES256_GCM,data:WR7IUbtr520+s8ZNsjyWyEFt9fOp4IrShUjYp0Od4glC4T89UFkawc0WaV625esVZun9mDElSK9oRpiv/dKzgN9WeIglf8YnbA==,iv:zMBbAm07CwS8w14SLQ975TIxHNN3LCGcKsVoJnfszF0=,tag:MFJXH4EiNiaYbxSrZX09Gg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4L29nQk0zbnFEeWZWWkpa
            TlpaK3RFZlFKT0djelo5cVo5QkRBQUFiKzA0ClpLOHMybTdBOVZyR3UvTDY2YmlI
            bUdUSnFTak5wZlYyclJLNlNzVC9XdUEKLS0tIGZPajQvUlkxd1RCeTlDWmNwV29t
            SzlrdHJiSFp4MnRUeXZEY25yVmF2dXcKkNW6DZgeh0Qt1jwQNB8GAuk+Ollaut7O
            C1vAgozMkGqbkXXazQ42i2r7H7Tgl3lZHCLB7L50K4mw6/nVPjWZtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fmqw6vxjs3sx6gatvfxftpy6sg8cyy0sw2m9w9nqh5wxh8ck8gpqrx9s8y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T20:34:26Z"
    mac: ENC[AES256_GCM,data:WF3txrldORxXf92sNGhfmlffZCVqvNVs36wrUEowqYF3oVVcm2DYYUWD255jmbcXvQnyMDWt2kHqyaCImP/4s7UFGWbEtvBGMLkNhjF/IOekV7XElnl99RuXEV+3gEhgYIyYJVz5H0SkjET9DzqeygFfNyUk6+O4Q0c39sccUVo=,iv:yGGWt7xOAxtdKeff1P2mw0U6DpCrMbi8bVsCRWCNN14=,tag:xZStkimiVD4VDnA6PeUMiw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: netbox-superuser
    namespace: netbox
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:dNpmSE8=,iv:0lwJ0ndog9yMFLYRKN8mUlAODHqWAMsA33WDzUXjEow=,tag:IZk4B6luRQGhReyHatKlBA==,type:str]
    email: ENC[AES256_GCM,data:s3J8ZayISl9/76ZB2uSEmMH/lG4O9ls=,iv:WCsn8COBn8bWtrH0aJamn9ONnXGYb8FlNLjTNMwRYjw=,tag:LmOsFrqgY3to7sFozxoK3Q==,type:str]
    password: ENC[AES256_GCM,data:fQM8LIsLz3bd/5onlThdEDSESzP3uBov,iv:6TCVp9NaVSVLFb2pjG5SuF5PwTJUGbkWA0xQHW8ukDY=,tag:UH4UTHQDf938OCs4YPn7tQ==,type:str]
    api_token: ENC[AES256_GCM,data:mBT1EDG2t2Q/G6vruALkyF237vRY7HZUh4z5OJDMlBi676Z4VAhthA==,iv:oWxsoNW+F+6Pbyp109/BGg9ezYhoqczdqV7+n9XNaFA=,tag:8OaJrAXwB/0mt7U7sF/2Jw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4L29nQk0zbnFEeWZWWkpa
            TlpaK3RFZlFKT0djelo5cVo5QkRBQUFiKzA0ClpLOHMybTdBOVZyR3UvTDY2YmlI
            bUdUSnFTak5wZlYyclJLNlNzVC9XdUEKLS0tIGZPajQvUlkxd1RCeTlDWmNwV29t
            SzlrdHJiSFp4MnRUeXZEY25yVmF2dXcKkNW6DZgeh0Qt1jwQNB8GAuk+Ollaut7O
            C1vAgozMkGqbkXXazQ42i2r7H7Tgl3lZHCLB7L50K4mw6/nVPjWZtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fmqw6vxjs3sx6gatvfxftpy6sg8cyy0sw2m9w9nqh5wxh8ck8gpqrx9s8y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T20:34:26Z"
    mac: ENC[AES256_GCM,data:WF3txrldORxXf92sNGhfmlffZCVqvNVs36wrUEowqYF3oVVcm2DYYUWD255jmbcXvQnyMDWt2kHqyaCImP/4s7UFGWbEtvBGMLkNhjF/IOekV7XElnl99RuXEV+3gEhgYIyYJVz5H0SkjET9DzqeygFfNyUk6+O4Q0c39sccUVo=,iv:yGGWt7xOAxtdKeff1P2mw0U6DpCrMbi8bVsCRWCNN14=,tag:xZStkimiVD4VDnA6PeUMiw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: netbox-postgresql
    namespace: netbox
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:GSK7K+hqMkdgN3C/tGtVNVnhGsKSFBoEDdMAIxf8Wr4=,iv:ZL6eGiD/0zU2kKiY9TyDfIjWd33egZQa5lPCOCmbsME=,tag:eZPlS7ia484gHYZIop7zkQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:BkkkeRILNJll31ssAlONuaK9/OvWl7AgpWDYy1l38yo=,iv:JjCU+MAlO0nLPFsEg1uKFxamPc13a4GOem9+H3Vq7eg=,tag:tj1iXg+2Q0xX8EVFn/NWtg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4L29nQk0zbnFEeWZWWkpa
            TlpaK3RFZlFKT0djelo5cVo5QkRBQUFiKzA0ClpLOHMybTdBOVZyR3UvTDY2YmlI
            bUdUSnFTak5wZlYyclJLNlNzVC9XdUEKLS0tIGZPajQvUlkxd1RCeTlDWmNwV29t
            SzlrdHJiSFp4MnRUeXZEY25yVmF2dXcKkNW6DZgeh0Qt1jwQNB8GAuk+Ollaut7O
            C1vAgozMkGqbkXXazQ42i2r7H7Tgl3lZHCLB7L50K4mw6/nVPjWZtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fmqw6vxjs3sx6gatvfxftpy6sg8cyy0sw2m9w9nqh5wxh8ck8gpqrx9s8y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T20:34:26Z"
    mac: ENC[AES256_GCM,data:WF3txrldORxXf92sNGhfmlffZCVqvNVs36wrUEowqYF3oVVcm2DYYUWD255jmbcXvQnyMDWt2kHqyaCImP/4s7UFGWbEtvBGMLkNhjF/IOekV7XElnl99RuXEV+3gEhgYIyYJVz5H0SkjET9DzqeygFfNyUk6+O4Q0c39sccUVo=,iv:yGGWt7xOAxtdKeff1P2mw0U6DpCrMbi8bVsCRWCNN14=,tag:xZStkimiVD4VDnA6PeUMiw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: netbox-valkey
    namespace: netbox
type: Opaque
stringData:
    valkey-password: ENC[AES256_GCM,data:5OageCEV/WPwwvOwAdoVx6tdmxnnW8egIsbnaHyvmc8=,iv:ZAPtAy5ep5eY+4oiPCG3M22oRWBkYN4qggUfZPUP/SY=,tag:n+yn5U/WViAyAc8oq3FVlQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4L29nQk0zbnFEeWZWWkpa
            TlpaK3RFZlFKT0djelo5cVo5QkRBQUFiKzA0ClpLOHMybTdBOVZyR3UvTDY2YmlI
            bUdUSnFTak5wZlYyclJLNlNzVC9XdUEKLS0tIGZPajQvUlkxd1RCeTlDWmNwV29t
            SzlrdHJiSFp4MnRUeXZEY25yVmF2dXcKkNW6DZgeh0Qt1jwQNB8GAuk+Ollaut7O
            C1vAgozMkGqbkXXazQ42i2r7H7Tgl3lZHCLB7L50K4mw6/nVPjWZtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fmqw6vxjs3sx6gatvfxftpy6sg8cyy0sw2m9w9nqh5wxh8ck8gpqrx9s8y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T20:34:26Z"
    mac: ENC[AES256_GCM,data:WF3txrldORxXf92sNGhfmlffZCVqvNVs36wrUEowqYF3oVVcm2DYYUWD255jmbcXvQnyMDWt2kHqyaCImP/4s7UFGWbEtvBGMLkNhjF/IOekV7XElnl99RuXEV+3gEhgYIyYJVz5H0SkjET9DzqeygFfNyUk6+O4Q0c39sccUVo=,iv:yGGWt7xOAxtdKeff1P2mw0U6DpCrMbi8bVsCRWCNN14=,tag:xZStkimiVD4VDnA6PeUMiw==,type:str]
    version: 3.13.3
