---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: wireguard
  namespace: wireguard
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wireguard
      app.kubernetes.io/instance: wireguard
  endpoints:
    - targetPort: 9586
      interval: 30s
      path: /metrics
