apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: my-strimzi-cluster-operator
  namespace: flux-system
spec:
  interval: 24h
  type: oci
  url: oci://quay.io/strimzi-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-strimzi-cluster-operator
  namespace: kafka
spec:
  interval: 30m
  chart: 
    spec:
      chart: strimzi-kafka-operator
      version: '0.50.0'
      sourceRef:
        kind: HelmRepository
        name: my-strimzi-cluster-operator
        namespace: flux-system
      interval: 12h
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values: