---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: infra
  interval: 10m
  path: ./infra/kafka/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: kafkas.kafka.strimzi.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: kafkanodepools.kafka.strimzi.io
