apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-exporter
  namespace: pihole
  labels:
    app: pihole-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole-exporter
  template:
    metadata:
      labels:
        app: pihole-exporter
    spec:
      containers:
      - name: pihole-exporter
        image: ekofr/pihole-exporter:latest
        ports:
        - containerPort: 9617
          name: metrics
          protocol: TCP
        env:
        - name: PIHOLE_PROTOCOL
          value: "http"
        - name: PIHOLE_HOSTNAME
          value: "pihole-web,10.0.10.22,10.0.10.64"
        - name: PIHOLE_PORT
          value: "80"
        - name: PIHOLE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole-password
              key: password
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-exporter
  namespace: pihole
  labels:
    app: pihole-exporter
spec:
  type: ClusterIP
  ports:
  - port: 9617
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: pihole-exporter
