apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: pihole-exporter
  namespace: pihole
spec:
  selector:
    matchLabels:
      app: pihole-exporter
  endpoints:
  - port: metrics
    interval: 10s
    path: /
