apiVersion: v1
kind: Secret
metadata:
    name: ghost-login
    namespace: ghost
type: Opaque
data:
    ghostUsername: ENC[AES256_GCM,data:HDMa8po=,iv:fJ3fyDkjiFJcZjaOcNnAuYmdxkNPe1cd1rB2nrybal4=,tag:1VPQwYKw7uLThhGypznHOg==,type:str]
    ghostPassword: ENC[AES256_GCM,data:dDEIRjATmnKmjeaH,iv:S8dJ1zt8VqE13TjVbHEf07Tpq/4l4ffXYdlP1mi5DYs=,tag:eZPbuEut209WvDcVnBpj4w==,type:str]
sops:
    age:
        - recipient: age1fmqw6vxjs3sx6gatvfxftpy6sg8cyy0sw2m9w9nqh5wxh8ck8gpqrx9s8y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UWRaRDYwMzVEY3lRYS9z
            dHhMS2V3VXpHZ2pZTHN1R2NabUpyOUNUWG5FCklVMjJQdzF5VUVaNGRFQkJKa2tu
            a1hOY2UxUzBmSkJock1NYllDdDlBZjAKLS0tIGFtVUwzQjkreDhqRFlwaHlyTUNl
            b0llaUZkVlJKUVdMTjZ3Z1RRTWs0ZlEKy57GYP7ZLqYsXEkHJfqsglbRUNNa/Wfs
            +57hk55jUSsLXda9sncWXxonWQM+YDShk+lV+t52dyQtLCh4fTiJlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T01:17:17Z"
    mac: ENC[AES256_GCM,data:dF1d5uDo3HsX0gEQ3g100ybz7/FjL5v2Jrfxv+eBL5G9ublJQzR5Vi87F5M5nhCDe18vSnecquLBCPb0V4HuftgJCKxQ7vstu0kRlayIx28TuRuPjpSsJIAi7352VVd2tuSyl1++3mUyBLtMsgG57rw6Up6iR7JPmYXrHRVrCuk=,iv:rkDmaifhyZzODAvbTgJnWYGSyjTGL7qqLgRUtjOmaxc=,tag:66xKNM0UE1P7kiUsMpt/qQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
